export const SLIDES_FETCHED = 'SLIDES_FETCHED'

export const SLIDE_ADDED = 'SLIDE_ADDED'
export const SLIDE_CONTENT_UPDATED = 'SLIDE_CONTENT_UPDATED'
export const SLIDE_DELETED = 'SLIDE_DELETED'

export const SLIDE_SELECTED = 'SLIDE_SELECTED'

export var ACTIVE_MODAL_CHANGED = 'ACTIVE_MODAL_CHANGED'
