export const SLIDES_FETCHED = 'SLIDES_FETCHED'

export const SLIDE_ADDED = 'SLIDE_ADDED'
export const SLIDE_CONTENT_UPDATED = 'SLIDE_CONTENT_UPDATED'
export const SLIDE_DELETED = 'SLIDE_DELETED'

export const ACTIVE_SLIDE_CHANGED = 'ACTIVE_SLIDE_CHANGED'

export const ACTIVE_MODAL_CHANGED = 'ACTIVE_MODAL_CHANGED'

export const SLIDE_GRABBED = 'SLIDE_GRABBED'
export const GRABBED_SLIDE_MOVED = 'GRABBED_SLIDE_MOVED'
export const SLIDE_DROPPED = 'SLIDE_DROPPED'

export const ACTIVE_CONTEXT_MENU_CHANGED = 'ACTIVE_CONTEXT_MENU_CHANGED'
